#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Focus on hover
bspc config focus_follows_pointer true

# Autostart Applications
sxhkd &
nitrogen --restore &
picom &
dunst &
$HOME/.config/polybar/launch.sh &

# Set cursor theme
xsetroot -cursor_name left_ptr
